language: c

compiler:
  - clang
  - gcc

sudo: required

services:
  - docker

env:
  global:
    # DEPLOY_HOST
    - secure: "ZdEqOs2M7q5Bf8RJqXSoZVr+XvXOJ7RppoDh/BSH+C19El6nvodvyiZg9OOavgOeL6uDnRRmJsbJztueHSfLIEicAWSgaqaO9R1Pa2OxIw3zEiKq0BLEjzgo3hYdD2EGpELJgJAGOM5DWAfp+Mxp/tDpt/cIBy3tBR5fTOF0JpMOoMzcyjsUreYvyxwSyzCHJBAG6Dqr8a951hjoV6WOlpFnJDkN4l7zfSiiKu3d158CcN7lL8adKWeb2fY8Nco8AvVgxxUklnur1MCtjeDT8QsNzHatzDt+1D/LxQRGkLzQJd0GrBExtFdEKX/dO1rXvpqeNev2ogAyfj4L2hU+8IUSg6oseYJQNYICyhVaIwPwRwiLqQZR6ggwFEskHmyGfJ1ykcj8UKJmIPJ47uYm+9IO5BcKR4HtqEJXFcdYoAztrdclxM0CzGM5TJBhilCiOO1+HzaTzvMJdRlWfYpI/KtCDMCT3HZwFK3qJNuGgfy3QvI/8nwWJct2qjEr8/rlpVHYdTdi7pTAWj2i0KYDgSvsnZY6KfbsR5jayhDDwSqBv8WgFb/tGebQxVMdmzFdsUoYzNqbwF9phXqo/ciG9Xxc0tvxgUrqVfoxlOF7Y2CWZyhn5ihB0El8vWPaoipw8HfGscbwNTz3mQg42pEvePTp/d2YBWr2VtqDvURrmQ4="

arch:
  artifacts:
    - qbs-shared-artifacts.tar.gz
    - fluid-artifacts.tar.gz
  packages:
    - qbs
    - qt5-quickcontrols2
    - qt5-tools
    - taglib
    - desktop-file-utils
    - xorg-server-xvfb
    - clang
    #- clazy-git
  script:
    #- export CLAZY_CHECKS="level1"
    - qbs-setup-toolchains --detect
    - qbs-setup-qt /usr/bin/qmake-qt5 qt5
    - qbs config profiles.qt5.baseProfile ${CC}
    - eval `dbus-launch --sh-syntax` && xvfb-run -a -s "-screen 0 800x600x24" qbs -d build -j $(nproc) profile:qt5
    - desktop-file-validate app/io.liri.Files.desktop

script:
  - "curl -s https://raw.githubusercontent.com/lirios/repotools/develop/travis/docker-travis.sh | bash"

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
